export const FALLBACK_FOLDERS = [
  {
    id: 'folder-p12',
    name: 'CSBH Tòa P12 - Quỹ Độc Quyền',
    description: 'Chính sách bán hàng ưu đãi dành riêng cho Tòa P12',
    applicableBuildings: 'P12',
    status: 'ACTIVE',
    priority: 1,
  },
]

export const FALLBACK_PLANS = [
  {
    id: 'plan-loan',
    name: 'Phương án Vay Ngân Hàng 70% (HTLS 0%)',
    type: 'LOAN',
    description: 'Hỗ trợ lãi suất 0%, ân hạn nợ gốc & miễn phí trả nợ trước hạn trong thời gian HTLS (5 đợt)',
    isActive: true,
    scheduleItems: [
      { stepNumber: 1, name: 'Đợt 1 (Ký TTĐC / Đặt cọc)', percentage: 0, dueDateNote: 'Ngay khi ký TTĐC (Studio: 50tr, 1PN: 100tr, 2PN: 150tr, 3PN: 200tr)' },
      { stepNumber: 2, name: 'Đợt 2 (Ký HĐMB - Đóng đủ 15% gồm cọc)', percentage: 15, dueDateNote: 'Dự kiến 25/08/2026 (sau 15 ngày)' },
      { stepNumber: 3, name: 'Đợt 3 (Ngân hàng giải ngân 70%)', percentage: 70, dueDateNote: 'Trong vòng 15 ngày sau khi ký HĐMB' },
      { stepNumber: 4, name: 'Đợt 4 (Vốn tự có 10%)', percentage: 10, dueDateNote: 'Dự kiến 25/10/2026 (sau 60 ngày)' },
      { stepNumber: 5, name: 'Đợt 5 (Bàn giao & Cấp GCN)', percentage: 5, dueDateNote: 'Dự kiến 30/09/2027 (Kèm 100% KPBT 2% & thuế của 5%)' },
    ],
  },
  {
    id: 'plan-std',
    name: 'Tiến độ thanh toán chuẩn (17 đợt)',
    type: 'STANDARD',
    description: 'Thanh toán giãn đều định kỳ 2 tháng/lần đến khi nhận bàn giao căn hộ và sổ hồng',
    isActive: true,
    scheduleItems: [
      { stepNumber: 1, name: 'Đợt 1 (Ký TTĐC / Đặt cọc)', percentage: 0, dueDateNote: 'Ngay khi ký TTĐC (Studio: 50tr, 1PN: 100tr, 2PN: 150tr, 3PN: 200tr)' },
      { stepNumber: 2, name: 'Đợt 2 (Ký HĐMB - Đóng đủ 15% gồm cọc)', percentage: 15, dueDateNote: 'Dự kiến 25/08/2026' },
      { stepNumber: 3, name: 'Đợt 3 (Thanh toán 10%)', percentage: 10, dueDateNote: 'Dự kiến 25/10/2026' },
      { stepNumber: 4, name: 'Đợt 4 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/12/2026' },
      { stepNumber: 5, name: 'Đợt 5 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/02/2027' },
      { stepNumber: 6, name: 'Đợt 6 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/04/2027' },
      { stepNumber: 7, name: 'Đợt 7 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/06/2027' },
      { stepNumber: 8, name: 'Đợt 8 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/08/2027' },
      { stepNumber: 9, name: 'Đợt 9 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/10/2027' },
      { stepNumber: 10, name: 'Đợt 10 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/12/2027' },
      { stepNumber: 11, name: 'Đợt 11 (Thanh toán 10%)', percentage: 10, dueDateNote: 'Dự kiến 25/02/2028' },
      { stepNumber: 12, name: 'Đợt 12 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/04/2028' },
      { stepNumber: 13, name: 'Đợt 13 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/06/2028' },
      { stepNumber: 14, name: 'Đợt 14 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/08/2028' },
      { stepNumber: 15, name: 'Đợt 15 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/10/2028' },
      { stepNumber: 16, name: 'Đợt 16 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 25/12/2028' },
      { stepNumber: 17, name: 'Đợt 17 (Bàn giao & Cấp GCN)', percentage: 5, dueDateNote: 'Dự kiến 30/09/2028 (Kèm 100% KPBT 2% & thuế của 5%)' },
    ],
  },
  {
    id: 'plan-tts-70',
    name: 'Thanh toán sớm 70% (Hạn 25/08/2026)',
    type: 'FAST',
    description: 'Hưởng chiết khấu 4.5% khi thanh toán đủ 70% trước 25/08/2026, phần còn lại trả chậm 2 tháng/lần (8 đợt)',
    isActive: true,
    scheduleItems: [
      { stepNumber: 1, name: 'Đợt 1 (Ký HĐTHNV / Đặt cọc)', percentage: 0, dueDateNote: 'Ngay khi ký HĐTHNV (Studio: 50tr, 1PN: 100tr, 2PN: 150tr, 3PN: 200tr)' },
      { stepNumber: 2, name: 'Đợt 2 (Thanh toán lần 2 - Đóng đủ 70% gồm cọc)', percentage: 70, dueDateNote: 'Muộn nhất ngày 25/08/2026' },
      { stepNumber: 3, name: 'Đợt 3 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 17/02/2028' },
      { stepNumber: 4, name: 'Đợt 4 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 17/04/2028' },
      { stepNumber: 5, name: 'Đợt 5 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 16/06/2028' },
      { stepNumber: 6, name: 'Đợt 6 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 15/08/2028' },
      { stepNumber: 7, name: 'Đợt 7 (Thanh toán 5%)', percentage: 5, dueDateNote: 'Dự kiến 14/10/2028' },
      { stepNumber: 8, name: 'Đợt 8 (Bàn giao & Cấp GCN)', percentage: 5, dueDateNote: 'Dự kiến 30/09/2028 (Kèm 100% KPBT 2% & thuế của 5%)' },
    ],
  },
  {
    id: 'plan-tts-95',
    name: 'Thanh toán sớm 95% (Hạn 25/09/2026)',
    type: 'FAST',
    description: 'Hưởng chiết khấu tối đa 9.5% khi hoàn thành thanh toán 95% muộn nhất 25/09/2026 (3 đợt)',
    isActive: true,
    scheduleItems: [
      { stepNumber: 1, name: 'Đợt 1 (Ký HĐTHNV / Đặt cọc)', percentage: 0, dueDateNote: 'Ngay khi ký HĐTHNV (Studio: 50tr, 1PN: 100tr, 2PN: 150tr, 3PN: 200tr)' },
      { stepNumber: 2, name: 'Đợt 2 (Thanh toán lần 2 - Đóng đủ 95% gồm cọc)', percentage: 95, dueDateNote: 'Muộn nhất ngày 25/09/2026' },
      { stepNumber: 3, name: 'Đợt 3 (Bàn giao & Cấp GCN)', percentage: 5, dueDateNote: 'Dự kiến 30/09/2027 (Kèm 100% KPBT 2% & thuế của 5%)' },
    ],
  },
]
